<nav class="font-mono uppercase font-bold text-sm grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-8">
    <a href="{{ route('index') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'index' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Dossier {{ Auth::id() ?? 'x' }}/250</a>
    <a href="{{ route('theory') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'theory' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Intro théorique</a>
    <a href="{{ route('info') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'info' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Intro pratique</a>
    <a href="{{ route('stats') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'stats' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Statistiques discriminations</a>
    <a href="{{ route('id') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'id' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Formulaire I.D.</a>
    <a href="{{ route('quotas') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'quotas' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Formulaire quotas privilèges</a>
    <a href="{{ route('brochure') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'brochure' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Brochure loterie sociale</a>
    <a href="{{ route('vote') }}" class="p-3 sm:pb-0 duration-150 hover:opacity-100 {{ Route::currentRouteName() === 'vote' ? 'shadow-[2px_-2px_2px_rgb(0,0,0,0.2)]' : 'opacity-60 shadow-[inset_0px_-2px_2px_rgb(0,0,0,0.2)]' }}">Formulaire vote final</a>
</nav>